[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "engine"
path = "src/main.rs"

[lib]
name = "engine"
path = "src/lib.rs"

[dependencies]
rover_core = { path = "../core" }
clap = "4.4.18"
serde = { version = "1.0", features = ["derive"] }
